export const movies = [
  { id: 1, title: { es: "Dune: Parte Dos", en: "Dune: Part Two" }, genreKey: "sciFi", year: 2024, rating: "8.5", poster: "https://image.tmdb.org/t/p/w500/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg", description: { es: "Paul Atreides se une a Chani y a los Fremen mientras busca venganza y enfrenta una decisión que cambiará el destino de Arrakis.", en: "Paul Atreides joins Chani and the Fremen while seeking revenge and facing a choice that will change Arrakis forever." } },
  { id: 2, title: { es: "Spider-Man: A través del Spider-Verso", en: "Spider-Man: Across the Spider-Verse" }, genreKey: "animation", year: 2023, rating: "8.7", poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", description: { es: "Miles Morales cruza el multiverso y descubre una red de héroes arácnidos con ideas opuestas sobre el sacrificio.", en: "Miles Morales crosses the multiverse and meets a network of spider heroes with opposing ideas about sacrifice." } },
  { id: 3, title: { es: "John Wick 4", en: "John Wick 4" }, genreKey: "action", year: 2023, rating: "7.7", poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg", description: { es: "John Wick encuentra un camino para derrotar a la Alta Mesa, pero antes debe enfrentar a nuevos enemigos en todo el mundo.", en: "John Wick finds a way to defeat the High Table, but first he must face new enemies around the world." } },
  { id: 4, title: { es: "Oppenheimer", en: "Oppenheimer" }, genreKey: "drama", year: 2023, rating: "8.1", poster: "https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg", description: { es: "El físico J. Robert Oppenheimer lidera el Proyecto Manhattan y queda marcado por las consecuencias de su creación.", en: "Physicist J. Robert Oppenheimer leads the Manhattan Project and is marked by the consequences of his creation." } },
  { id: 5, title: { es: "Barbie", en: "Barbie" }, genreKey: "comedy", year: 2023, rating: "7.0", poster: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg", description: { es: "Barbie viaja al mundo real y descubre preguntas inesperadas sobre identidad, propósito y libertad.", en: "Barbie travels to the real world and discovers unexpected questions about identity, purpose, and freedom." } },
  { id: 6, title: { es: "El Conjuro", en: "The Conjuring" }, genreKey: "horror", year: 2013, rating: "7.5", poster: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg", description: { es: "Dos investigadores paranormales ayudan a una familia aterrorizada por una presencia oscura en su granja.", en: "Two paranormal investigators help a family terrorized by a dark presence in their farmhouse." } },
  { id: 7, title: { es: "Misión Imposible: Sentencia Mortal", en: "Mission: Impossible - Dead Reckoning" }, genreKey: "action", year: 2023, rating: "7.5", poster: "https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg", description: { es: "Ethan Hunt y su equipo persiguen una amenaza tecnológica capaz de alterar el equilibrio global.", en: "Ethan Hunt and his team pursue a technological threat capable of changing the global balance." } },
  { id: 8, title: { es: "Elementos", en: "Elemental" }, genreKey: "animation", year: 2023, rating: "7.6", poster: "https://image.tmdb.org/t/p/w500/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg", description: { es: "En una ciudad donde conviven fuego, agua, tierra y aire, dos jóvenes descubren que tienen más en común de lo que parece.", en: "In a city where fire, water, earth, and air live together, two young people discover they share more than expected." } },
];

export const translations = {
  es: { brandAria: "Inicio de CineNova", languageButton: "EN", favoritesSingular: "favorita", favoritesPlural: "favoritas", heroEyebrow: "Cartelera seleccionada", pageTitle: "Encuentra tu próxima película", heroText: "Explora películas por género, guarda tus favoritas y abre cada ficha para ver más detalles.", catalogAria: "Catálogo de películas", genresLabel: "Géneros", catalogTitle: "Películas destacadas", searchPlaceholder: "Buscar película...", searchAria: "Buscar película", searchButton: "Buscar", filtersAria: "Filtros por género", loading: "Cargando películas...", noResults: "No se encontraron películas con esos filtros.", likeAria: "Me gusta", posterAlt: "Poster de", addFavorite: "Agregar a favoritas", removeFavorite: "Quitar de favoritas", closeModal: "Cerrar modal", closeFavorites: "Cerrar favoritos", favoritesEyebrow: "Tus selecciones", favoritesTitle: "Películas favoritas", noFavorites: "Todavía no seleccionaste películas favoritas.", remove: "Quitar", genres: { all: "Todas", sciFi: "Ciencia ficción", animation: "Animación", action: "Acción", drama: "Drama", comedy: "Comedia", horror: "Terror" } },
  en: { brandAria: "CineNova home", languageButton: "ES", favoritesSingular: "favorite", favoritesPlural: "favorites", heroEyebrow: "Selected lineup", pageTitle: "Find your next movie", heroText: "Browse movies by genre, save your favorites, and open each card to see more details.", catalogAria: "Movie catalog", genresLabel: "Genres", catalogTitle: "Featured movies", searchPlaceholder: "Search movie...", searchAria: "Search movie", searchButton: "Search", filtersAria: "Genre filters", loading: "Loading movies...", noResults: "No movies were found with those filters.", likeAria: "Like", posterAlt: "Poster for", addFavorite: "Add to favorites", removeFavorite: "Remove from favorites", closeModal: "Close modal", closeFavorites: "Close favorites", favoritesEyebrow: "Your picks", favoritesTitle: "Favorite movies", noFavorites: "You have not selected favorite movies yet.", remove: "Remove", genres: { all: "All", sciFi: "Science fiction", animation: "Animation", action: "Action", drama: "Drama", comedy: "Comedy", horror: "Horror" } },
};
